# -*- coding: utf-8 -*-
'''
@File     : NameSwitch.py
@Copyright: Qiuwenjing
@Date     : 2021/10/20
@Desc     : 映射财务字端中英文
'''

FINACEKPI = {
    "assetLiabilityRatio": "资产负债率",
    "basicEarningsPerShare": "每股收益-基本",
    "capitalReservePerShare": "每股资本公积金",
    "dilutedEarningsPerShare": "每股收益-稀释",
    # "endDate": "日期",
    "evEbit": "EV/EBIT企业价值倍数",
    "evEbitda": "EV/EBITDA",
    # "financeTime": "报告日期",
    "grossProfitMargin": "销售毛利率",
    "netAssetsPerShare": "每股净资产",
    "netProfit": "净利润",
    "netProfitRate": "净利润率",
    "netProfitYoyGrowthRate": "净利润同比增长率",
    "operCashflowPerShare": "每股经营性现金流",
    "operIncome": "营业收入",
    "operIncomeYoyGrowthRate": "营业收入同比增长率",
    "priceBookRatio": "市净率",
    "priceEarningRatio": "市盈率",
    "salesMargin": "销售净利率",
    "undistributedProfitPerShare": "每股未分配利润",
    "weightedRoe": "净资产收益率-加全"
}

PROFITREPORT = {
    "assetsImpairmentLoss": "资产减值损失",
    "basicEarningsPerShare": "每股收益-基本",
    "businessTaxAndCost": "营业税金及附加",
    "dilutedEarningsPerShare": "每股收益-稀释",
    "ebit": "ebit",
    "ebitda": "ebitda",
    "endDate": "报告日期",
    "financeTime": "报告期",
    "financialExpenses": "财务费用",
    "incomeTaxExpense": "减：所得税费用",
    "investIncome": "投资收益",
    "managementCosts": "管理费用",
    "minorityInterestIncome": "少数股东损益",
    "netProfit": "净利润",
    "netProfitRate": "净利润率",
    "nonBusinessExpenditure": "减：营业外支出",
    "nonBusinessIncome": "加：营业外收入",
    "operCosts": "营业成本",
    "operIncome": "营业收入",
    "operProfit": "营业利润",
    "parentComOwnerNetProfit": "归属于母公司所有者的净利润",
    "salesExpense": "销售费用",
    "totalOperCosts": "营业总成本",
    "totalOperIncome": "营业总收入",
    "totalProfit": "营业利润"
}

FINACEDEBT = {
    "accountsPayable": "应付账款",
    "accountsReceivable": "应收账款",
    "assetSum": "资产总计",
    "capitalReserve": "资本公积",
    "constructionInProgress": "在建工程",
    "debtSum": "负债合计",
    "deferredIncomeTaxLiabilities": "递延所得税负债",
    "deferredTaxAssets": "递延所得税资产",
    "devExpenditure": "开发支出",
    "endDate": "报告日期",
    "financeTime": "报告期",
    "fixedAssets": "固定资产",
    "goodwill": "商誉",
    "intangibleAssets": "无形资产",
    "investmentRealEstate": "投资性房地产",
    "longTermEquityInvestment": "长期股权投资",
    "longTermLoan": "长期借款",
    "longTermPrepaidExpenses": "长期待摊费用",
    "minorityEquity": "少数股东权益",
    "moneyFunds": "货币资金",
    "nonCurrentLiabilitiesDueWithinOneYear": "一年内到期的非流动负债",
    "notesReceivable": "应收票据",
    "otherPayables": "其它应付款",
    "otherReceivables": "其它应收款",
    "paidInCapital": "实收资本",
    "parentComOwnerTotalEquity": "归属于母公司所有者权益合计",
    "payrollPayable": "应付职工薪酬",
    "prepayments": "预付款项",
    "shortTermLoan": "短期借款",
    "stock": "存货",
    "surplusReserve": "盈余公积",
    "taxesPayable": "应交税费",
    "totalCurrentAssets": "流动资产合计",
    "totalCurrentLiabilities": "流动负债合计",
    "totalLiabilitiesAndOwnerEquity": "负债和所有者（或股东）权益合计",
    "totalNonCurrentAssets": "非流动资产合计",
    "totalNonCurrentLiabilities": "非流动负债合计",
    "totalOwnerEquity": "所有者（或股东）权益合计",
    "tradingFinancialAssets": "交易性金融资产",
    "undistributedProfit": "未分配利润",
    "interestReceivable": "应收利息",
    "advanceReceipt": "预售款项",
    "estimatedLiabilities": "预计负债"
}

CASHFLOW = {
    "addNetcash": "增加的现金流量净额",
    "addOperNetcash": "经营活动产生的现金流量净额",
    "amortizationOfIntangibleAssets": "无形资产摊销",
    "amortizationOfLongTermAmortization": "长期待摊费用摊销",
    "assetImpairmentProvisions": "加：资产减值准备",
    "businessActivitiesCashInflowSubtotal": "经营活动产生的现金流入小计",
    "businessActivitiesCashOutflowSubtotal": "经营活动产生的现金流出小计",
    "cashAndCashEquivalentBeginningBalance": "加：期初现金及现金等价物余额",
    "cashAndCashEquivalentEndingBalance": "期末现金及现金等价物余额",
    "cashAndCashEquivalentsNetIncrease": "现金及现金等价物净增加额",
    "cashBeginningBalance": "减：现金的期初余额",
    "cashEndingBalance": "现金的期末余额",
    "cashPaidForConstructionOfFixedIntangibleAndOtherLongTermAssets": "购建固定资产、无形资产和其他长期资产支付的现金",
    "cashPaidForDebt": "偿还债务支付的现金",
    "cashPaidForDividendsProfitsOrInterestPayments": "分配股利、利润或偿付利息支付的现金",
    "cashPaidForInvestment": "投资支付的现金",
    "cashPaidForOtherBusinessActivities": "支付其他与经营活动有关的现金",
    "cashPaidForOtherFundraisingActivities": "支付其他与筹资活动有关的现金",
    "cashPaidForPurchaseOfGoodsAndServices": "购买商品、接受劳务支付的现金",
    "cashPaidToAndForEmployees": "支付给职工以及为职工支付的现金",
    "cashReceivedFromAbsorbingInvestment": "吸收投资收到的现金",
    "cashReceivedFromDisinvestment": "收回投资收到的现金",
    "cashReceivedFromInvestmentIncome": "取得投资收益收到的现金",
    "cashReceivedFromLoan": "取得借款收到的现金",
    "cashReceivedFromOtherBusinessActivities": "收到的其他经营活动有关的现金",
    "cashReceivedFromOtherFundraisingActivities": "收到其他与筹资活动有关的现金",
    "cashReceivedFromSaleOfGoodsAndServices": "销售商品、提供劳务收到的现金",
    "depreciationOfFixedAssets": "固定资产折旧",
    "effectOfExchangeRateChanges": "汇率变动对现金及现金等价物的影响",
    "endDate": "报告日期",
    "financeTime": "报告期",
    "financialExpenses": "财务费用",
    "fundraisingActivitiesCashInflowSubtotal": "筹资活动现金流入小计",
    "fundraisingActivitiesCashOutflowSubtotal": "筹资活动现金流出小计",
    "increaseInDeferredIncomeTaxLiabilities": "递延所得税负债增加",
    "increaseInOperatingPayables": "经营性应付项目的增加",
    "investmentActivitiesCashInflowSubtotal": "投资活动现金流入小计",
    "investmentActivitiesCashOutflowSubtotal": "投资活动现金流出小计",
    "investmentLosses": "投资损失",
    "lossOnDisposalOfFixedIntangibleAndOtherLongTermAssets": "处置固定资产、无形资产和其他长期资产的损失",
    "lossOnRetirementOfFixedAssets": "固定资产报废损失",
    "netCashFlowFromBusinessActivities": "间接法-经营活动产生的现金流量净额",
    "netCashFlowFromFundraisingActivities": "筹资活动产生的现金流量净额",
    "netCashFlowFromInvestingActivities": "投资活动产生的现金流量净额",
    "netCashRecoveredFromDisposalOfFixedIntangibleAndOtherLongTermAssets": "处置固定资产、无形资产和其他长期资产回收的现金净额",
    "netProfit": "净利润",
    "paidForVariousTaxes": "支付的各项税费",
    "reductionInDeferredIncomeTaxAssets": "递延所得税资产减少",
    "reductionInOperatingReceivables": "经营性应收项目的减少",
    "reductionInStock": "存货的减少",
    "taxRefund": "收到的税费返还"
}